### ISSUE TITLE
How to connect pixhawk with QGround control while the simulator is running. 

### ISSUE THREAD

**Issue by Sneha-hub115** [ros-simulation/gazebo_ros_pkgs#1054]
Hi,
I’m using ubuntu18.04 to build the px4 code for gazebo and jmavsim. I’m stuck with the following issues:

    1. How to connect pixhawk with QGround control while the simulator(jMAVSim,Gazebo) is running.
    2. How to connect pixhawk with QGround control while the drone is flying.

Thank you

**Comment by chapulina** [comment]
Please ask questions at http://answers.gazebosim.org instead of an issue tracker, as is explained in the issue template which you seem to have ignored. Also note that this repository doesn't have anything related to pixhawk.

I see you asked the same question at https://github.com/PX4/Firmware/issues/14291. Please note that cross-posting the same question in several places is not the best way to get the answers you need.
