### ISSUE TITLE
libgazebo_ros_planar_move Issue

### ISSUE THREAD

**Issue by SeungRyeol** [ros-simulation/gazebo_ros_pkgs#1113]
Describe your issue here and explain how to reproduce it.

**Description**

I am using libgazebo_ros_planar_move. When a robot is affected by gravity, it falls at a very slow rate.

**To Reproduce**

1. Configure the robot environment using libgazebo_ros_planar_move.
2. Load the robot on the gazebo.
3. If you drop the robot from a high place, it will fall very slowly.

**Expected behavior**

The robot must fall quickly under the influence of gravity.

**Screenshots**

**Environment (please complete the following information):**

 - OS: Ubuntu 18.04
 - Gazebo version: Gazebo 9
 - ROS version: Melodic
  - gazebo_ros_pkgs: [e.g. debian install | source install at commit X]
 - glx server in use: output from `glxinfo | grep 'server glx vendor'` (glxinfo is in mesa-utils package for Debian/Ubuntu)

**Additional context**

How can I solve this problem?

**Comment by LihanChen2004** [comment]
@SeungRyeol Have you resolved it? I meet the same problem too in ROS2. But when I set `update_rate` lower like 10. It will be better. But I wonder it's not a good method to resolve it, because the `update_rate` will affect the control frequency...

Edit: Maybe related to https://github.com/ros-simulation/gazebo_ros_pkgs/issues/121
