### ISSUE TITLE
ROS Dashing diff_drive_controller tf ignores namespace.

### ISSUE THREAD

**Issue by joe28965** [ros-simulation/gazebo_ros_pkgs#1120]
**Description**

If I want to use a namespace for my robot, using either (or both) of the following lines of code as an argument:

```
'-robot_namespace', LaunchConfiguration('namespace'),
['__ns:=/', LaunchConfiguration('namespace')],
```

Everything gets a namespace except for the tf from the diff_drive_controller. I do not fully understand why this is the only one that doesn't seem to use the namespace.

**To Reproduce**

1. Add a robot using spawn_entity
```
Node(
	package='gazebo_ros', 
	node_executable='spawn_entity.py',
	arguments=['-entity', LaunchConfiguration('namespace'),
						'-file', str(urdf_path),
						'-x', LaunchConfiguration('x'),
						'-y', LaunchConfiguration('y'),
						'-z', '0.08',
						'-robot_namespace', LaunchConfiguration('namespace'),
						['__ns:=/', LaunchConfiguration('namespace')],
	],
	output='screen',
),

```
2. Make sure you've added a namespace
3. Open rqt node graph
4. See diff_drive_controller connected to /tf and everything else having a namespace

**Expected behavior**

I would expect my topic from the diff_drive_controller to change from /tf to /namespace/tf

**Environment:**

 - OS: Ubuntu 18.04
 - Gazebo version: Gazebo 9
 - ROS version: Dashing
  - gazebo_ros_pkgs: debian install

**Comment by jacobperron** [comment]
`/tf` is a special topic used by the [tf2 library](https://github.com/ros2/geometry2), which defaults to the global namespace. It's not typically recommended to change the name of the `/tf` topic since much ROS tooling, like the tf2 library and RViz, expect messages on this topic.

If you insist on renaming the `/tf` topic, you should be able to do so with an explicit remap. The only way to do this that comes to mind is to add a `<remapping>` tag to your robot description. E.g.

    <ros>
      <remapping>/tf:=/example_namespace/tf</remapping>
    </ros>

But, you probably don't want to hard-code the namespace in the description, for the sake of re-usability. You could use [xacro](http://wiki.ros.org/xacro) to parameterize the namespace in the description file. 

I'm not sure how feasible it is to add support for passing remappings (and parameters) to the spawn entity tool. It would require updating the [service definition](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/b9e72ae0bbc764a80d0cafaa9ca49f4877ef0529/gazebo_msgs/srv/SpawnEntity.srv), that's for sure.
