### ISSUE TITLE
Change default branch to `noetic-devel`

### ISSUE THREAD

**Issue by bjsowa** [ros-simulation/gazebo_ros_pkgs#1277]
The current default branch `kinetic-devel` points to an EOL distro. I think it's time to change it to `noetic-devel` (or at least `melodic-devel`).

Also, there is a lot of stale branches, seems like most of them could be safely removed.

**Comment by joe28965** [comment]
I already mentioned stale branches in #1176 and still completely agree with you there. Some were removed after, but extra branches have also emerged since.

There are 9 indigo-X branches for instance. One is indigo-devel, but the other ones are all weird variations. For a distro that had its EOL 2 years ago.

**Comment by bjsowa** [comment]
Closing due to #1294
