### ISSUE TITLE
Avoid creating multiple nodes with the same name

### ISSUE THREAD

**Issue by jacobperron** [ros-simulation/gazebo_ros_pkgs#1303]
We have a specific use-case where we create a custom plugin that inherits from `GazeboRosCameraPlugin`. This child class needs a reference to a ROS node, but if we use `gazebo_ros::Node::Get(sdf)` then we end up with two ROS nodes with the same name: the node created by the parent and the node created by the child. Both are using the SDF to determine the name of the node.

I think in general, if multiple gazeob_ros plugins happen to use the same name in SDF, then we will end up with multiple nodes with the same name. This is generally discouraged in ROS 2 and can result in ambiguous scenarios, e.g. when setting parameters remotely, they will be arbitrarily set on one of the nodes with the same name.

To workaround this issue, we introduced a getter for the node so that children can access it (instead of creating a new node): https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1299. However, this does not fix the problem; it only provides a workaround.

To properly support this use case we should either, 1) forbid creating multiple nodes with the same name or 2) make it easy to avoid creating multiple nodes with the same name.

If we go with option (2), we could achieve this by maintaining a global map of node names to node objects (alongside the other globals in `gazebo_ros::Node`). Then whenever a user tries to get a new node, we can first check if one already exists with the same name and give them a handle to it.  However, this method may run into thread-safety issues.

**Comment by deepanshubansal01** [comment]
If multiple plugins with the same name are used in sdf/world file then ros2 does throw a warning but does not do anything to avoid it. The warning comes from rclcpp logging, and says the following:

[WARN] [1652907467.743035652] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.

Based on our offline discussion, we are proceeding with **option (1)** i.e forbid creating multiple nodes with the same name.
