### ISSUE TITLE
gazebo_ros cmake target conflict with tf2 in catkin workspace

### ISSUE THREAD

**Issue by tkruse** [ros-simulation/gazebo_ros_pkgs#136]
See
http://answers.ros.org/question/93691/cannot-create-target-when-using-gazebo_ros-and-tf2/

To reproduce, place geometry_experimental and the given package calling 

```
find_package(catkin REQUIRED COMPONENTS gazebo_ros)
```

in the same catkin workspace.

**Comment by meyerj** [comment]
I had a similar problem a few days ago. In order to solve it, either add `gazebo_ros` as a build dependency to rrbot_gazebo's [package.xml](https://github.com/ros-simulation/gazebo_ros_demos/blob/2c6f6a9890e8582eaa8c2990632736b437eeeecc/rrbot_gazebo/package.xml) or remove the `gazebo_ros` entry in the `find_package(catkin REQUIRED COMPONENTS gazebo_ros)` line in its [CMakeLists.txt](https://github.com/ros-simulation/gazebo_ros_demos/blob/2c6f6a9890e8582eaa8c2990632736b437eeeecc/rrbot_gazebo/CMakeLists.txt#L6).

Without the build dependency in the package manifest catkin might order the rrbot_gazebo package before gazebo_ros when building in the same workspace and due to the `find_package()` call it creates dummy custom targets for all targets  exported by gazebo_ros and its dependencies if they do not exist yet in that workspace (check catkin-generated `devel/share/cmake/tf2_msgsConfig.cmake` file). This dummy targets collide with the real targets that are created when catkin tries to configure the tf2_msgs package itself.

As far as I know catkin prints a warning if you call `find_package(catkin REQUIRED COMPONENTS foo)` and `foo` is not listed as a build dependency in `package.xml`.

**Comment by j-rivero** [comment]
I think that using isolated build is the workaround not to fail into this issue. Not sure if we can do anything in gazebo_ros_pkgs about it. Please, reopen if we come up with a proposal about how to fix it.

**Comment by scpeters** [comment]
This could be reported at https://github.com/ros-simulation/gazebo_ros_demos if the problem is with `rrbot_gazebo`. In the meantime, isolated builds are safer.
