### ISSUE TITLE
Issues with debians gazebo_ros_pkgs and gazebo under ROS Hydro

### ISSUE THREAD

**Issue by airballking** [ros-simulation/gazebo_ros_pkgs#145]
Hi,

when trying to simulate the PR2 in Gazebo under Hydro on Precise I made the following observations:

(1)
- The version of gazebo_ros in the package.xml is 2.4
- "roslocate info gazebo_ros" points to the hydro_devel branch of this repo
- The hydro_devel branch of this repo has version 2.3.3 in the package.xml

(2)
- When installing "ros-hydro-gazebo-ros-pkgs" apt-get wants to uninstall debian package "gazebo" and install "gazebo-current"
- In that configuration: Trying to spawn the PR2 urdf from pr2_description in Gazebo reproducibly crashes gazebo.

(3)
- Setup: Uninstall debian packages "ros-hydro-gazebo-ros-pkgs" and "gazebo-current", reinstall debian "gazebo", and install and compile "gazebo_ros_pkgs" from source.
- Now spawning the PR2 urdf from pr2_description in Gazebo works fine.

My questions:
- How can the debian ros-hydro-gazebo-ros be ahead of the hydro-devel branch on github? 
- Why does the debian ros-hydro-gazebo-ros-pkgs enforce the debian gazebo-current over the package gazebo?
- Is the crash in setup (2) because of the newer version of gazebo-ros or gazebo-current?

Thanks in advance for your support.

Best,
Georg.

**Comment by j-rivero** [comment]
Hello Georg:

I would recommend read the gazebo document about [gazebo and ROS](http://gazebosim.org/wiki/Install/Gazebo_and_ROS) which I believe contains big part of the information you are looking for.

Let me answer your questions anyway:
- It was used for generating the metadata needed by gazebo team too release version 2.4.0 of gazebo_ros_pkgs. This version is only in the OSRF repo.
- gazebo-current is enforced by 2.4.0 of gazebo_ros_pkgs since the ABI is not compatible between gazebo (1.9) and gazebo-current (2.0)
- The crash probably comes from the ABI breakage.

We are working on renaming ros-gazebo-pkgs 2.4.0 into a different name so all this mess does not happen again.

**Comment by airballking** [comment]
Hello Jose,

thanks for clearing this up so quickly. Following the instructions you pointed to I managed to install gazebo 1.9 and gazebo-ros-pksgs 2.3.3 from debians.

I originally followed the install instructions for gazebo 1.9 from here:
http://gazebosim.org/wiki/1.9/install

Maybe adding the link you provided to me to those instructions will prevent others from accidentally installing Gazebo 2.0?

Thanks again,
Georg.

**Comment by j-rivero** [comment]
Good idea, done. Thanks Georg for taking the time to submit the detailed bug report.
