### ISSUE TITLE
Tutorials - RRBot not launching correctly in RViz

### ISSUE THREAD

**Issue by hboortz** [ros-simulation/gazebo_ros_pkgs#25]
After following the instructions here: http://gazebosim.org/wiki/Tutorials/1.9/Using_A_URDF_In_Gazebo, RRBot does not launch correctly in RViz as shown below. It does launch correctly in Gazebo.

![image](https://f.cloud.github.com/assets/1470111/682734/1eb40be0-d9ce-11e2-9424-fa4650a3001e.png)

**Comment by hboortz** [comment]
Caused by roscore having been run for gazebo previously and resolved by "killall roscore" and then relaunching.

**Comment by davetcoleman** [comment]
I see you added the note to the tutorial:

> If you do not get this, try killing all old roscore processes with killall roscore and relaunching RViz.

So this can be closed.

**Comment by roboticsai** [comment]
when i do killall roscore it showed:
roscore: no process found
and shows error:
[rviz-3] process has died [pid 22161, exit code -11, cmd /opt/ros/indigo/lib/rviz/rviz -d /home/dinesh/catkin_wsg/src/gazebo_ros_demos/rrbot_description/launch/rrbot.rviz __name:=rviz __log:=/home/dinesh/.ros/log/5e3cd4ac-6a0f-11e6-b5c2-5c260a2762ef/rviz-3.log].
log file: /home/dinesh/.ros/log/5e3cd4ac-6a0f-11e6-b5c2-5c260a2762ef/rviz-3*.log
what is the problem here?
