### ISSUE TITLE
pcl 1.7 integration

### ISSUE THREAD

**Issue by piyushk** [ros-simulation/gazebo_ros_pkgs#72]
PCL has been updated to 1.7 on shadow-fixed, breaking all plugins that used pointclouds. Is a patch required?

**Comment by davetcoleman** [comment]
Fixed in https://github.com/ros-simulation/gazebo_ros_pkgs/pull/73

Note: I've just created a `groovy-devel` branch with the current code frozen if anyone wants to continue using gazebo_ros_pkgs without Hydro, because this pull requests breaks compatibility with Groovy.

Going forward all work should continue in `hydro-devel` and soon `indigo-devel`

**Comment by davetcoleman** [comment]
Closing this issue because pcl 1.7 has been integrated.

Side note: we will be switching back to using pcl_conversions soon, as documented in this issue https://github.com/ros-simulation/gazebo_ros_pkgs/issues/81
