### ISSUE TITLE
Mass, inertia does not effect with Planar move

### ISSUE THREAD

**Issue by kamoonty** [ros-simulation/gazebo_ros_pkgs#952]
Hi, I am quite new to ROS and Gazebo. Currently, I have developed my own robot URDF to create Mecanum robot. The planar move should be okay with my purpose. However, when I change mass and inertia in URDF file. It does not affect the robot movement. For example, robot mass = 1000 kg or 1 kg. The robot still moving. And when I stop the robot I want it to have inertia not to stop suddenly.   
Note: I also have tried with the ros_force_based_move plugin which had developed from planar move plugin. The mass and inertia have an effect to the robot. However, I got a problem with TF Publisher instead.

**Comment by chapulina** [comment]
Welcome, @kamoonty ! This issue tracker is for bugs and feature requests. For technical help using the plugins and setting up your simulation, please ask a question at http://answers.gazebosim.org.

The planar move plugin overrides physics by directly setting velocities. That's why it is ignoring your robot's dynamics. On the other hand, the force plugin uses dynamics, and that's why you see the inertial properties having an effect.

I recommend you open a question on Gazebo Answers explaining what's the TF problem you're having so someone can help you.

**Comment by kamoonty** [comment]
Thank you
