### ISSUE TITLE
Cannot set material for custom Collada files 

### ISSUE THREAD

**Issue by JaehyunShim** [ros-simulation/gazebo_ros_pkgs#990]
Hi, 

Is there any way I can set material for my (non cube or sphere shaped) custom Collada files.
I tried below but I think I need to do more extra things 
```sh
<material>
  <script>
    <uri>file://media/materials/scripts/gazebo.material</uri>
     <name>Gazebo/Wood</name>
  </script>
</material>
```
You can see above lines work differently for normal boxes and the curvy object from the picture below.
![Screenshot from 2019-09-04 15-58-27](https://user-images.githubusercontent.com/38637417/64232633-420ae900-cf2d-11e9-9c1f-83a8ae61fc70.png)

Thank you in advance,
Ryan

**Comment by chapulina** [comment]
Hi @rjshim , please ask technical questions like this at https://answers.gazebosim.org . This issue tracker is for bug reports and feature requests.

In any case, your problem seems to be your mesh's UV map, similar to the problem in [this question](http://answers.gazebosim.org/question/23554/texture-does-not-work-properly/).
